create user if not exists viking_user password 'viking_password';

grant all on schema public to viking_user;

create table if not exists vikings (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    age int not null,
    height_cm int not null,
    hair_color varchar(50) not null,
    beard_style varchar(50) not null,
    description text
);

create table if not exists equipment_items (
    id bigint generated by default as identity primary key,
    viking_id bigint not null,
    name varchar(255) not null,
    quality varchar(100),

    constraint fk_equipment_viking
        foreign key (viking_id)
        references vikings(id)
        on delete cascade
);


